Widescreen Support
geoge23/wadaily pull request #5
Opened 2022-11-09 19:20 UTC by willv678

Adds an additional widescreen page for the school's hallway TV screens, creating a no-scroll site to better conform to the TV's aspect ratios.

2022-11-10 15:07 UTC, geoge23 requested changes
This code is on the right track. Just a few changes and we'll be ready to merge.
Thanks for your help!

2022-11-10 15:07 UTC, geoge23 commented on components/Hero.js
> +//Will Varner Date Function (Prob stupid?? idk it works well :D returns "Tuesday, November 8th") for the widescreen thing
This is the correct way to do this, however it should be memoized so that the component isn't re-calling each time. See https://www.sitepoint.com/implement-memoization-in-react-to-improve-performance/

Also make sure you're only creating variables you will use

2022-11-10 15:07 UTC, geoge23 commented on components/WeatherIcon.js
> +    return (<WeatherIconSelector icon={icon}></WeatherIconSelector>)}
This is the correct way to manage this by extracting to a component, however you're declaring a component that returns another component for no reason. Export WeatherIconSelector from here rather than making WeatherIcon that returns another component for no reason. 
Also, make sure to update WeatherBar to use this component to prevent code duplication.

2022-11-10 15:07 UTC, geoge23 commented on pages/widescreen.js
> +  const ctx = useContext(PreferencesContext);
I'll cut down on some of the code in here, since not all of it is necessary for the widescreen mode and will use up API credits/server resources

2022-11-10 15:07 UTC, geoge23 commented on public/credits.html
> +Mobile Developer, Helped with UI/UX design and manual entry tasks</li>
Lol yea ok. U can add widescreen support for ur credits here if u want. Just make sure to update the markdown (credits.md) in tandem for some legacy stuff I have set up

2022-11-10 15:10 UTC, geoge23 commented
Also, check the widescreen page since the text overflows off the page. I don't know if you intend for it to autoscroll (if so, this is fine, ignore comment) or somehow squeeze the text together

2022-11-25 17:18 UTC, willv678 reviewed
Converted DateString to a memo function via a new component

2022-11-29 18:59 UTC, merged